#!/usr/bin/env bash
#Configure domain zone so that the subdomain www points to your load-balancer IP
#shellcheck disable=SC2059
get_dns_config () {
    dns_record=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $dns_record" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  get_dns_config "$1" "www"
  get_dns_config "$1" "lb-01"
  get_dns_config "$1" "web-01"
  get_dns_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  get_dns_config "$1" "$2"
fi
