#!/usr/bin/env bash
#Config NGINX server with custom header response
sudo apt-get -y update
sudo apt-get -y install nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.habtish.tech permanent;' /etc/nginx/sites-available/default
sudo sed -i '/^\slocation.*/i \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo sed -i '/^\slocation.*/i \        error_page 404 /404.html;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo service nginx start
