#!/usr/bin/env bash
# So the problem was the nginx engine has not been started 
# So I tried many ways to restart it but they didn't work 
# The only command that seem to work is what I did and successfuly restarted
service nginx start
