#!/usr/bin/env bash
# So the problem was the nginx engine was configuredon  the port was
# at 8080, So I tried many ways to restart it but they didn't work; he only
# command that seem to work is what I did and successfuly restarted

sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx start
