#!/usr/bin/env bash
#Find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -s reload
