#!/usr/bin/env bash
# run Nginx as nginx

# change the config file; replace user by Nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# replace 80 with 8080, in the default config file
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# permissions to nginx to read and write on the config file
chmod 644 /etc/nginx/nginx.conf

# kill apache just so it won't interfere with Nginx
pkill apache2

# start nginx
sudo -u nginx service nginx start
