#!/usr/bin/env bash
# the configuration of the nginx changed so it runs as nginx user
pkill apache2
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 755 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
