#!/usr/bin/env bash
# This is a bash script that creates an RSA key pair.
# Name of the private key must be school
# Number of bits in the created key should be 4096
# The created key must be protected by the passphrase betty

ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N betty
